#!/bin/bash

chunkc core::log_file stdout
chunkc core::log_level warn
chunkc core::plugin_dir /usr/local/opt/chunkwm/share/chunkwm/plugins
chunkc core::hotload 1

# chunkwm-tiling
chunkc set global_desktop_mode           bsp
chunkc set global_desktop_offset_top     8
chunkc set global_desktop_offset_bottom  5
chunkc set global_desktop_offset_left    5
chunkc set global_desktop_offset_right   5
chunkc set global_desktop_offset_gap     5

chunkc set desktop_padding_step_size     10.0
chunkc set desktop_gap_step_size         5.0

chunkc set bsp_spawn_left                0
chunkc set bsp_optimal_ratio             1.618
chunkc set bsp_split_mode                optimal
chunkc set bsp_split_ratio               0.5

chunkc set monitor_focus_cycle           1
chunkc set window_focus_cycle monitor

chunkc set mouse_follows_focus           intrinsic
chunkc set window_float_next             0
chunkc set window_region_locked          1

# chwm-sa (https://github.com/koekeishiya/chwm-sa)
chunkc set window_float_topmost          0
chunkc set window_fade_inactive          1
chunkc set window_fade_alpha             0.85
chunkc set window_fade_duration          0.25
chunkc set window_use_cgs_move           0

# chunkwm-border
chunkc set focused_border_color          0xAABF616A
chunkc set focused_border_width          8
chunkc set focused_border_radius         0
chunkc set focused_border_skip_floating  1

# chunkwm-ffm
chunkc set ffm_bypass_modifier fn

# enable plugins
chunkc core::load tiling.so
chunkc core::load ffm.so
chunkc core::load border.so

chunkc tiling::rule --owner Spotify --role AXWindow --subrole AXDialog --state tile
chunkc tiling::rule --owner Finder --name Copy --state float
chunkc tiling::rule --owner \"App Store\" --state float
chunkc tiling::rule --owner \"System Preferences\" --state float
chunkc tiling::rule --owner \"Twitter\" --state float
chunkc tiling::rule --owner \"Steam\" --state float
chunkc tiling::rule --owner \"Tweetbot\" --state float
chunkc tiling::rule --owner \"zoom.us\" --state float
chunkc tiling::rule --owner \"Platypus\" --state float
