#!/usr/bin/env bash

# ~/.macos — inspired by https://mths.be/macos

# Close any open System Preferences panes, to prevent them from overriding
# settings we’re about to change
osascript -e 'tell application "System Preferences" to quit'

# Ask for the administrator password upfront
sudo -v

# Keep-alive: update existing `sudo` time stamp until `.macos` has finished
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &

###############################################################################
# General UI/UX                                                               #
###############################################################################

# Set standby delay to 24 hours (default is 1 hour).
sudo pmset -a standbydelay 86400

# Disable the sound effects on boot.
sudo nvram SystemAudioVolume=" "

# Reduce Transparency in Menu and Windows.
defaults write com.apple.universalaccess reduceTransparency -bool true

# Disable icons on the desktop; a Ulysses pact with myself to avoid clutter.
defaults write com.apple.finder CreateDesktop -bool FALSE

# Disable gamed; it generates constant network traffic and I don't use GameCenter.
launchctl unload -w /System/Library/LaunchAgents/com.apple.gamed.plist 2> /dev/null

# Disable Notification Center. This will also remove the menubar icon prior to
# El Capitan, but not after (--). I'm now using Bartender to remove the icon.
launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist 2> /dev/null

###############################################################################
# Bartender                                                                   #
###############################################################################

# TODO: Hide Time Machine, Volume, User and Notification Center icons.

###############################################################################
# Adobe                                                                       #
###############################################################################

# I don't always use Adobe, but when I do, it's as little as possible.

# Disable Adobe CS3 daemons (I don't know what they do, but pretty sure they
# don't serve me).
launchctl unload -w /Library/LaunchDaemons/com.adobe.* 2> /dev/null

# Delete this outdated osascript file.
sudo rm -rf "/Library/ScriptingAdditions/Adobe Unit Types.osax"

###############################################################################
# Kill affected applications                                                  #
###############################################################################

for app in "Activity Monitor" "Address Book" "Calendar" "Contacts" "cfprefsd" \
	"Dock" "Finder" "Google Chrome" "Google Chrome Canary" "Mail" "Messages" \
	"Opera" "Photos" "Safari" "SizeUp" "Spectacle" "SystemUIServer" "Terminal" \
	"Transmission" "Tweetbot" "Twitter" "iCal"; do
	killall "${app}" &> /dev/null
done

echo "Done. Note that some of these changes require a logout/restart to take effect."
