#!/bin/sh

# This file is executed by GDM. It contains setup that is shared between
# environments.

# Default terminal.
export TERMINAL=termite

# Default editor.
export EDITOR=nvim

# Stack puts executables here.
export PATH="$HOME/.local/bin:$PATH"

# Setup scripts for the window manager/desktop environment.
export PATH="$HOME/.lib/bin:$PATH"

# My command line utilities.
export PATH="$HOME/bin:$PATH"

# Tell systemctl that we've updated these variables.
systemctl --user import-environment PATH HOME DISPLAY XAUTHORITY

# Initialize the keyboard
. $HOME/.lib/bin/init-keyboard.sh

xrdb -merge ~/.Xresources
