#! /bin/zsh

# Displays current audio volume.

. $HOME/.xmobar/icons

# Get the current pulseaudio volume. Requires `pamixer`.
VOLUME=$(pamixer --get-volume)

# Uncomment for alsa. Requires `amixer` from `alsa-utils`.
#VOLUME=$(amixer get Master -M | grep -oE '[[:digit:]]*%' | tr -d '%')

# Use different icons for high and low volume.
if [ $VOLUME -ge 50 ]; then
  echo -e "<fn=1>$ICON_VOLUME_HIGH</fn> $VOLUME"
else
  echo -e "<fn=1>$ICON_VOLUME_LOW</fn> $VOLUME"
fi
