#! /bin/zsh

# Displays wifi connection info.

. $HOME/.xmobar/icons

WIFI_INFO=$(iw dev "wlp4s0" link)

if [[ $WIFI_INFO = "Not connected." ]]; then
  echo -e "<fn=1>$ICON_WIFI_DISCONNECTED</fn> diconnected"
else
  # Get the ssid.
  # WIFI_SSID=$(echo $WIFI_INFO | grep "SSID" | sed 's/SSID: //')

  # Get the signal strength.
  WIFI_SIGNAL=$(echo $WIFI_INFO | grep "signal" | sed 's/signal: //' | tr -d ' dBm')

  if (( $WIFI_SIGNAL > -50 )); then
    WIFI_SIGNAL_PERCENT="100"
  elif (( $WIFI_SIGNAL < -100 )); then
    WIFI_SIGNAL_PERCENT="0"
  else
    WIFI_SIGNAL_PERCENT=$(echo $((2 * (100 + $WIFI_SIGNAL))))
  fi

  echo -e "<fn=1>$ICON_WIFI_CONNECTED</fn> $WIFI_SIGNAL_PERCENT"
fi
