#!/bin/sh

xrdb -merge .Xresources

feh --bg-fill ~/Pictures/wallpaper.jpg &

compton &

xscreensaver -no-splash &

eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs12,secrets,ssh)
export SSH_AUTH_SOCK

exec xmonad
