#!/bin/sh

export PATH=$HOME/bin:$PATH

xrdb -merge .Xresources

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

feh --bg-fill ~/Pictures/wallpaper.jpg &

compton &

xscreensaver -no-splash &

if [ -f /usr/bin/gnome-keyring-daemon ]; then
  eval $(/usr/bin/gnome-keyring-daemon --start --components=pkcs12,secrets,ssh)
  export SSH_AUTH_SOCK
fi

nm-applet &

dunst -config $HOME/.dunstrc &

exec xmonad
