#!/bin/sh

# This file is executed by GDM. It contains setup that is shared between
# environments.

export PATH="$HOME/bin:$PATH"

if [ -d /etc/X11/xinit/xinitrc.d ]; then
  for f in /etc/X11/xinit/xinitrc.d/*; do
    [ -x "$f" ] && . "$f"
  done
  unset f
fi

# Set a fast keyboard repeat rate.
xset r rate 200 50

xrdb -merge $HOME/.Xresources
