#!/bin/sh

# This file is executed by GDM. It contains setup that is shared between
# environments.

# Default terminal.
export TERMINAL=kitty

# Default editor.
export EDITOR=nvim

# Setup scripts for the window manager/desktop environment.
export PATH="$HOME/.lib/bin:$PATH"

# My command line utilities.
export PATH="$HOME/bin:$PATH"

# Tell systemctl that we've updated these variables.
systemctl --user import-environment PATH HOME DISPLAY XAUTHORITY

# Set a fast keyboard repeat rate.
xset r rate 200 50

xrdb -merge ~/.Xresources
