#! /bin/zsh

# Displays current battery status. Requires `acpi`.

. $HOME/.xmobar/icons

if [ -e /sys/class/power_supply/BAT0 ] || [ -e /sys/class/power_supply/BAT1 ]; then
  ACPI_STAT=$(acpi)
  OUT=""

  while read -r line; do
    test $OUT && OUT+=" "
    # get the status: charging, discharging
    BAT_STAT=$(echo $line | awk '{print $3}' | tr -d ',')
    # get the current battery load percentage
    BAT_PERC=$(echo $line | awk '{print $4}' | tr -d '%,')
    if [[ $BAT_STAT = "Discharging" ]]; then
      OUT+="$ICON_BATTERY_FULL $BAT_PERC"
    else
      OUT+="$ICON_BATTERY_CHARGING $BAT_PERC"
    fi
  done <<< "$ACPI_STAT"

  echo "$OUT"
else
  echo -e "$ICON_BATTERY_CHARGING"
fi
