#! /bin/zsh

# Displays currently playing track. Requires `mpc`.

. $HOME/.xmobar/icons

MUSIC=$(mpc)
MUSIC_LINES=$(echo $MUSIC | wc -l)

# When music is playing, mpc shows 3 lines, when stopped only one line.
if [[ $MUSIC_LINES -eq 3 ]]; then
  # Get status: playing or paused.
  MUSIC_STATUS=$(echo $MUSIC | awk 'NR==2' | awk '{print $1}' | tr -d '[]')

  if [[ $MUSIC_STATUS = "playing" ]]; then
    MUSIC_STATUS_ICON=$ICON_MEDIA_PLAY
  else
    MUSIC_STATUS_ICON=$ICON_MEDIA_PAUSE
  fi

  # Get current playing song.
  MUSIC_CURRENT=$(echo $MUSIC | awk 'NR==1')

  # Get current position in song.
  MUSIC_POS=$(echo $MUSIC | awk 'NR==2' | awk '{print $3}')

  echo -e "<fn=1>$MUSIC_STATUS_ICON</fn> $MUSIC_CURRENT - $MUSIC_POS"
else
  echo -e "<fn=1>$ICON_MEDIA_STOP</fn> stopped"
fi
